---
controller_credentials:
  - name: "Default Execution Environment Registry Credential"
    description: ""
    credential_type: "Container Registry"
    organization: "SSA"
    inputs:
      host: registry.redhat.io
      password: ''
      username: bwolinsk@redhat.com
      verify_ssl: true

...

